[package]
name = "ffmpeg_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
ffmpeg-next = { git = "https://github.com/axel10/rust-ffmpeg", branch = "master", default-features = false, features = ["codec", "format", "software-resampling"] }

[target.'cfg(not(any(target_os = "ios", target_os = "macos")))'.dependencies]
ffmpeg-next = { git = "https://github.com/axel10/rust-ffmpeg", branch = "master", default-features = false, features = ["codec", "filter", "format", "software-resampling"] }
