// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `capabilities_notes`, `codec_spec_for_format`, `encoder_quality_for_bitrate`, `find`, `normalize_path`, `output_bitrate_mode`, `output_channel_layout`, `output_format_key`, `output_sample_format`, `output_sample_rate`, `supported_output_formats`, `supports_output_format_on_current_platform`, `unsupported_output_format_error`, `uses_lossy_bitrate_controls`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioCodecSpec>>
abstract class AudioCodecSpec implements RustOpaqueInterface {
  Id get fallbackId;

  set fallbackId(Id fallbackId);
}
