// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid_request_result`, `transcode_impl`, `transcode`

String greet({required String name}) =>
    RustLib.instance.api.crateApiAudioConverterSimpleGreet(name: name);

Future<String> convertFile({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiAudioConverterSimpleConvertFile(requestJson: requestJson);

Stream<String> convertFileWithProgress({required String requestJson}) =>
    RustLib.instance.api.crateApiAudioConverterSimpleConvertFileWithProgress(
      requestJson: requestJson,
    );

Stream<String> decodeToPcmStream({
  required String inputPath,
  required String outputPcmPath,
  int? targetSampleRate,
  int? targetChannels,
}) => RustLib.instance.api.crateApiAudioConverterSimpleDecodeToPcmStream(
  inputPath: inputPath,
  outputPcmPath: outputPcmPath,
  targetSampleRate: targetSampleRate,
  targetChannels: targetChannels,
);

String getCapabilities() =>
    RustLib.instance.api.crateApiAudioConverterSimpleGetCapabilities();

void createNamedPipe({required String path}) => RustLib.instance.api
    .crateApiAudioConverterSimpleCreateNamedPipe(path: path);
