# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # 1. Clean up SFBAudioEngine package references from user project (Runner.xcodeproj)
  user_project = installer.aggregate_targets.first.user_project
  user_project.root_object.package_references.each do |ref|
    if (ref.respond_to?(:repositoryURL) && ref.repositoryURL.include?('SFBAudioEngine')) ||
       (ref.respond_to?(:relative_path) && ref.relative_path.include?('SFBAudioEngine'))
      user_project.root_object.package_references.delete(ref)
      ref.remove_from_project
    end
  end
  # Remove package product dependency from targets in user project if any
  user_project.targets.each do |target|
    if target.respond_to?(:package_product_dependencies)
      target.package_product_dependencies.each do |dep|
        if dep.product_name == 'SFBAudioEngine'
          target.package_product_dependencies.delete(dep)
          dep.remove_from_project
        end
      end
    end
  end

  # Clean up "Embed and Sign SPM Frameworks" build phase from Runner target if it exists
  runner_target = user_project.targets.find { |t| t.name == 'Runner' }
  if runner_target
    existing_phase = runner_target.shell_script_build_phases.find { |p| p.name == 'Embed and Sign SPM Frameworks' }
    if existing_phase
      runner_target.build_phases.delete(existing_phase)
      existing_phase.remove_from_project
    end
  end
  user_project.save

  # 2. Clean up SFBAudioEngine package references from Pods.xcodeproj
  pods_project = installer.pods_project
  pods_project.root_object.package_references.each do |ref|
    if (ref.respond_to?(:repositoryURL) && ref.repositoryURL.include?('SFBAudioEngine')) ||
       (ref.respond_to?(:relative_path) && ref.relative_path.include?('SFBAudioEngine'))
      pods_project.root_object.package_references.delete(ref)
      ref.remove_from_project
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end

    if target.name == 'audio_core'
      # Remove package product dependency on SFBAudioEngine if any
      if target.respond_to?(:package_product_dependencies)
        target.package_product_dependencies.each do |dep|
          if dep.product_name == 'SFBAudioEngine'
            target.package_product_dependencies.delete(dep)
            dep.remove_from_project
          end
        end
      end

      # Add library search path and linker flag for local FFmpeg static library on iOS
      sfb_ffmpeg_device_path = File.expand_path('../../../darwin/FFmpeg.xcframework/ios-arm64', __FILE__)
      sfb_ffmpeg_sim_path = File.expand_path('../../../darwin/FFmpeg.xcframework/ios-arm64_x86_64-simulator', __FILE__)
      target.build_configurations.each do |config|
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]'] = "$(inherited) \"#{sfb_ffmpeg_sim_path}\""
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphoneos*]'] = "$(inherited) \"#{sfb_ffmpeg_device_path}\""

        flags = config.build_settings['OTHER_LDFLAGS']
        if flags.nil?
          config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-lffmpeg']
        elsif flags.is_a?(Array)
          flags << '-lffmpeg' unless flags.include?('-lffmpeg')
        else
          config.build_settings['OTHER_LDFLAGS'] = "#{flags} -lffmpeg"
        end
      end
    end
  end
end
