// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../lib.dart';
import '../controller.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_waveformat_extensible`, `probe_exclusive_format`, `pwstr_to_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ComSend`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `into_inner`

Future<List<AudioDeviceDesc>> enumerateWasapiRenderDevices() => RustLib
    .instance
    .api
    .crateApiSimpleWasapiSinkWasapiImplEnumerateWasapiRenderDevices();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WasapiExclusiveSink>>
abstract class WasapiExclusiveSink implements RustOpaqueInterface {
  Future<void> deviceName();

  Future<void> formatConfig();

  Future<Mixer> mixer();

  static Future<WasapiExclusiveSink> open({
    Str? targetDeviceId,
    required int sampleRate,
    required int channels,
    required bool releaseOnPause,
  }) => RustLib.instance.api
      .crateApiSimpleWasapiSinkWasapiImplWasapiExclusiveSinkOpen(
        targetDeviceId: targetDeviceId,
        sampleRate: sampleRate,
        channels: channels,
        releaseOnPause: releaseOnPause,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WasapiFormatConfig>>
abstract class WasapiFormatConfig implements RustOpaqueInterface {
  int get bitDepth;

  int get channels;

  int get sampleRate;

  SampleType get sampleType;

  Waveformatextensible get waveFormat;

  set bitDepth(int bitDepth);

  set channels(int channels);

  set sampleRate(int sampleRate);

  set sampleType(SampleType sampleType);

  set waveFormat(Waveformatextensible waveFormat);
}

enum SampleType { float32, int32, int24In32, int24In24, int16 }
