[package]
name = "audio_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
anyhow = "1.0.102"
log = "0.4.29"
base64 = "0.22.1"
serde_json = "1.0.145"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
zune-core = "0.5.1"
zune-image = { version = "0.5.0", default-features = false, features = ["jpeg", "png"] }
zune-imageprocs = { version = "0.5.1", default-features = false }
palette_core = { path = "palette" }
fast_image_resize = "6.0.0"
libblur = "0.23.3"
ffmpeg_core = { path = "ffmpeg_core" }
rusty-chromaprint = "0.3.0"
md5 = "0.7.0"
webp = "0.3.0"


[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
rodio = { path="./rodio", default-features = true, features = ["symphonia-all"] }
rodio-wsola = { path = "./rodio-wsola" }
realfft = "3.5.0"
fundsp = "0.23.0"
cpal = { version = "0.18.1", features = ["realtime"] }
timestretch = { path = "timestretch-rs" }
env_logger = "0.11"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
android_logger = "0.15.0"
ndk-context = "0.1.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Media_Audio",
    "Win32_Devices_FunctionDiscovery",
    "Win32_System_Com",
] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
