// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'equalizer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Future<void> initApp() =>
    RustLib.instance.api.crateApiSimpleControllerInitApp();

Future<void> loadAudioFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleControllerLoadAudioFile(path: path);

Future<void> crossfadeToAudioFile({
  required String path,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiSimpleControllerCrossfadeToAudioFile(
  path: path,
  durationMs: durationMs,
);

Future<void> playAudio({required PlatformInt64 fadeMs}) =>
    RustLib.instance.api.crateApiSimpleControllerPlayAudio(fadeMs: fadeMs);

Future<void> pauseAudio({required PlatformInt64 fadeMs}) =>
    RustLib.instance.api.crateApiSimpleControllerPauseAudio(fadeMs: fadeMs);

Future<bool> toggleAudio() =>
    RustLib.instance.api.crateApiSimpleControllerToggleAudio();

Future<void> seekAudioMs({required PlatformInt64 ms}) =>
    RustLib.instance.api.crateApiSimpleControllerSeekAudioMs(ms: ms);

Future<void> setAudioVolume({required double volume}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioVolume(volume: volume);

Future<PlatformInt64> getAudioPositionMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioPositionMs();

Future<PlatformInt64> getAudioDurationMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioDurationMs();

Future<int> getAudioPcmChannelCount({String? path}) => RustLib.instance.api
    .crateApiSimpleControllerGetAudioPcmChannelCount(path: path);

Future<bool> isAudioPlaying() =>
    RustLib.instance.api.crateApiSimpleControllerIsAudioPlaying();

Future<String?> getLoadedAudioPath() =>
    RustLib.instance.api.crateApiSimpleControllerGetLoadedAudioPath();

Future<Float32List> getLatestFft() =>
    RustLib.instance.api.crateApiSimpleControllerGetLatestFft();

Future<Float32List> getAudioPcm({String? path, required BigInt stride}) =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioPcm(
      path: path,
      stride: stride,
    );

Future<void> setAudioEqualizerConfig({required EqualizerConfig config}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioEqualizerConfig(
      config: config,
    );

Future<EqualizerConfig> getAudioEqualizerConfig() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioEqualizerConfig();

Future<void> disposeAudio() =>
    RustLib.instance.api.crateApiSimpleControllerDisposeAudio();

Future<PlaybackState> snapshotPlaybackState() =>
    RustLib.instance.api.crateApiSimpleControllerSnapshotPlaybackState();

Future<void> prepareForFileWrite() =>
    RustLib.instance.api.crateApiSimpleControllerPrepareForFileWrite();

Future<void> finishFileWrite() =>
    RustLib.instance.api.crateApiSimpleControllerFinishFileWrite();

Future<void> handleDeviceChanged() =>
    RustLib.instance.api.crateApiSimpleControllerHandleDeviceChanged();

enum FadeMode { sequential, crossfade }

class FadeSettings {
  final bool fadeOnSwitch;
  final bool fadeOnPauseResume;
  final PlatformInt64 durationMs;
  final FadeMode mode;

  const FadeSettings({
    required this.fadeOnSwitch,
    required this.fadeOnPauseResume,
    required this.durationMs,
    required this.mode,
  });

  static Future<FadeSettings> default_() =>
      RustLib.instance.api.crateApiSimpleControllerFadeSettingsDefault();

  @override
  int get hashCode =>
      fadeOnSwitch.hashCode ^
      fadeOnPauseResume.hashCode ^
      durationMs.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FadeSettings &&
          runtimeType == other.runtimeType &&
          fadeOnSwitch == other.fadeOnSwitch &&
          fadeOnPauseResume == other.fadeOnPauseResume &&
          durationMs == other.durationMs &&
          mode == other.mode;
}

class PlaybackState {
  final String? playbackState;
  final PlatformInt64 positionMs;
  final PlatformInt64 durationMs;
  final bool isPlaying;
  final double volume;
  final String? path;
  final String? error;

  const PlaybackState({
    this.playbackState,
    required this.positionMs,
    required this.durationMs,
    required this.isPlaying,
    required this.volume,
    this.path,
    this.error,
  });

  static Future<PlaybackState> default_() =>
      RustLib.instance.api.crateApiSimpleControllerPlaybackStateDefault();

  @override
  int get hashCode =>
      playbackState.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      isPlaying.hashCode ^
      volume.hashCode ^
      path.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          playbackState == other.playbackState &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          isPlaying == other.isPlaying &&
          volume == other.volume &&
          path == other.path &&
          error == other.error;
}
