// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'equalizer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_snapshot_loaded_path`, `any_deck_playing`, `apply_master_volume`, `channel_count`, `clear_pending_playback_state`, `clear`, `compute_rms`, `config`, `controller`, `create_player`, `describe_output_device`, `dispose_audio`, `drive_crossfade`, `drive_volume_fade`, `engine`, `ensure_audio_output`, `finish_file_write`, `get_audio_waveform_fallback_with_pcm`, `get_desired_exclusive_format`, `into_source`, `invalidate_waveform_cache`, `is_playing`, `mark_track_ended`, `mix_to_mono_samples`, `mixer`, `new`, `new`, `new`, `normalize_playback_speed`, `open_current_default_output`, `open_deck_from_backend`, `open_deck_from_path`, `open_symphonia`, `open`, `open`, `pause_all`, `pause`, `play_all`, `play`, `playback_position`, `playback_state_snapshot`, `poll_output_device`, `prepare_for_file_write`, `public_deck`, `public_path`, `public_position`, `record_fft_request`, `reduce_waveform_chunks`, `replace_current_from_backend`, `replace_current_from_path`, `report_audio_stream_error`, `round_waveform_precision`, `sample_rate`, `seek_to`, `seek_to`, `set_master_volume`, `settle_to_public_deck`, `snapshot_playback_state`, `start_crossfade_with_backend`, `start_crossfade`, `start_default_output_monitor`, `start_volume_fade`, `stress_diagnostic_details`, `toggle_all`, `total_duration`, `total_duration`, `warm_waveform_cache_for_public_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DecoderBackend`, `EndNotifySource`, `FfmpegAudioSource`, `OutputSinkConfig`, `OutputSink`, `PendingEdit`, `PlaybackDeck`, `PlayerController`, `PrefetchSource`, `SpeedSource`, `SpeedState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `channels`, `channels`, `channels`, `channels`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `current_span_len`, `current_span_len`, `current_span_len`, `current_span_len`, `drop`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `next`, `next`, `next`, `next`, `sample_rate`, `sample_rate`, `sample_rate`, `sample_rate`, `size_hint`, `total_duration`, `total_duration`, `total_duration`, `total_duration`, `try_seek`, `try_seek`, `try_seek`, `try_seek`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

Future<Float32List> getAudioPcm({String? path, required BigInt sampleStride}) =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioPcm(
      path: path,
      sampleStride: sampleStride,
    );

Future<Float64List> getAudioWaveform({
  String? path,
  required BigInt expectedChunks,
  required BigInt sampleStride,
}) => RustLib.instance.api.crateApiSimpleControllerGetAudioWaveform(
  path: path,
  expectedChunks: expectedChunks,
  sampleStride: sampleStride,
);

Future<int> getAudioPcmChannelCount({String? path}) => RustLib.instance.api
    .crateApiSimpleControllerGetAudioPcmChannelCount(path: path);

Future<void> initApp() =>
    RustLib.instance.api.crateApiSimpleControllerInitApp();

Future<void> loadAudioFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleControllerLoadAudioFile(path: path);

Future<void> crossfadeToAudioFile({
  required String path,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiSimpleControllerCrossfadeToAudioFile(
  path: path,
  durationMs: durationMs,
);

Future<void> playAudio({required PlatformInt64 fadeDurationMs}) => RustLib
    .instance
    .api
    .crateApiSimpleControllerPlayAudio(fadeDurationMs: fadeDurationMs);

Future<void> pauseAudio({required PlatformInt64 fadeDurationMs}) => RustLib
    .instance
    .api
    .crateApiSimpleControllerPauseAudio(fadeDurationMs: fadeDurationMs);

Future<bool> toggleAudio() =>
    RustLib.instance.api.crateApiSimpleControllerToggleAudio();

Future<void> seekAudioMs({required PlatformInt64 positionMs}) => RustLib
    .instance
    .api
    .crateApiSimpleControllerSeekAudioMs(positionMs: positionMs);

Future<void> setAudioVolume({required double volume}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioVolume(volume: volume);

Future<void> setPlaybackSpeed({required double speed}) =>
    RustLib.instance.api.crateApiSimpleControllerSetPlaybackSpeed(speed: speed);

Future<double> getPlaybackSpeed() =>
    RustLib.instance.api.crateApiSimpleControllerGetPlaybackSpeed();

Future<EqualizerConfig> getAudioEqualizerConfig() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioEqualizerConfig();

Future<void> setAudioEqualizerConfig({required EqualizerConfig config}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioEqualizerConfig(
      config: config,
    );

Future<void> disposeAudio() =>
    RustLib.instance.api.crateApiSimpleControllerDisposeAudio();

Future<bool> isAudioPlaying() =>
    RustLib.instance.api.crateApiSimpleControllerIsAudioPlaying();

Future<PlatformInt64> getAudioDurationMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioDurationMs();

Future<PlatformInt64> getAudioPositionMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioPositionMs();

Future<Float32List> getLatestFft() =>
    RustLib.instance.api.crateApiSimpleControllerGetLatestFft();

Future<String?> getLoadedAudioPath() =>
    RustLib.instance.api.crateApiSimpleControllerGetLoadedAudioPath();

Future<String> getAudioDecodeEngine() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioDecodeEngine();

Future<void> handleDeviceChanged() =>
    RustLib.instance.api.crateApiSimpleControllerHandleDeviceChanged();

Future<List<AudioDeviceDesc>> getAudioOutputDevices() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioOutputDevices();

Future<void> setAudioOutputMode({
  required AudioOutputMode mode,
  String? deviceId,
  required bool releaseOnPause,
  required bool bitPerfect,
}) => RustLib.instance.api.crateApiSimpleControllerSetAudioOutputMode(
  mode: mode,
  deviceId: deviceId,
  releaseOnPause: releaseOnPause,
  bitPerfect: bitPerfect,
);

Future<ActiveAudioHardwareFormat?> getActiveAudioHardwareFormat() =>
    RustLib.instance.api.crateApiSimpleControllerGetActiveAudioHardwareFormat();

Future<void> prepareForFileWrite() =>
    RustLib.instance.api.crateApiSimpleControllerPrepareForFileWrite();

Future<void> finishFileWrite() =>
    RustLib.instance.api.crateApiSimpleControllerFinishFileWrite();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpeedShared>>
abstract class SpeedShared implements RustOpaqueInterface {
  Future<double> getSpeed();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SpeedShared> newInstance({required double speed}) =>
      RustLib.instance.api.crateApiSimpleControllerSpeedSharedNew(speed: speed);

  Future<void> setSpeed({required double speed});
}

class ActiveAudioHardwareFormat {
  final AudioOutputMode mode;
  final String deviceName;
  final int sampleRate;
  final int bitDepth;
  final int channels;
  final bool isBitPerfect;

  const ActiveAudioHardwareFormat({
    required this.mode,
    required this.deviceName,
    required this.sampleRate,
    required this.bitDepth,
    required this.channels,
    required this.isBitPerfect,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      deviceName.hashCode ^
      sampleRate.hashCode ^
      bitDepth.hashCode ^
      channels.hashCode ^
      isBitPerfect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveAudioHardwareFormat &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth &&
          channels == other.channels &&
          isBitPerfect == other.isBitPerfect;
}

class AudioDeviceDesc {
  final String id;
  final String name;
  final bool isDefault;

  const AudioDeviceDesc({
    required this.id,
    required this.name,
    required this.isDefault,
  });

  static Future<AudioDeviceDesc> default_() =>
      RustLib.instance.api.crateApiSimpleControllerAudioDeviceDescDefault();

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDeviceDesc &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault;
}

enum AudioOutputMode {
  shared,
  wasapiExclusive;

  static Future<AudioOutputMode> default_() =>
      RustLib.instance.api.crateApiSimpleControllerAudioOutputModeDefault();
}

enum FadeMode { sequential, crossfade }

class FadeSettings {
  final bool fadeOnSwitch;
  final bool fadeOnPauseResume;
  final PlatformInt64 durationMs;
  final FadeMode mode;

  const FadeSettings({
    required this.fadeOnSwitch,
    required this.fadeOnPauseResume,
    required this.durationMs,
    required this.mode,
  });

  static Future<FadeSettings> default_() =>
      RustLib.instance.api.crateApiSimpleControllerFadeSettingsDefault();

  @override
  int get hashCode =>
      fadeOnSwitch.hashCode ^
      fadeOnPauseResume.hashCode ^
      durationMs.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FadeSettings &&
          runtimeType == other.runtimeType &&
          fadeOnSwitch == other.fadeOnSwitch &&
          fadeOnPauseResume == other.fadeOnPauseResume &&
          durationMs == other.durationMs &&
          mode == other.mode;
}

class PlaybackState {
  final String? playbackState;
  final PlatformInt64 positionMs;
  final PlatformInt64 durationMs;
  final bool isPlaying;
  final double volume;
  final String? path;
  final String? error;

  const PlaybackState({
    this.playbackState,
    required this.positionMs,
    required this.durationMs,
    required this.isPlaying,
    required this.volume,
    this.path,
    this.error,
  });

  static Future<PlaybackState> default_() =>
      RustLib.instance.api.crateApiSimpleControllerPlaybackStateDefault();

  @override
  int get hashCode =>
      playbackState.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      isPlaying.hashCode ^
      volume.hashCode ^
      path.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          playbackState == other.playbackState &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          isPlaying == other.isPlaying &&
          volume == other.volume &&
          path == other.path &&
          error == other.error;
}
