// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class EqualizerConfig {
  final bool enabled;
  final int bandCount;
  final double preampDb;
  final double bassBoostDb;
  final double bassBoostFrequencyHz;
  final double bassBoostQ;
  final Float32List bandGainsDb;

  const EqualizerConfig({
    required this.enabled,
    required this.bandCount,
    required this.preampDb,
    required this.bassBoostDb,
    required this.bassBoostFrequencyHz,
    required this.bassBoostQ,
    required this.bandGainsDb,
  });

  static Future<EqualizerConfig> default_() =>
      RustLib.instance.api.crateApiSimpleEqualizerEqualizerConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      bandCount.hashCode ^
      preampDb.hashCode ^
      bassBoostDb.hashCode ^
      bassBoostFrequencyHz.hashCode ^
      bassBoostQ.hashCode ^
      bandGainsDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualizerConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          bandCount == other.bandCount &&
          preampDb == other.preampDb &&
          bassBoostDb == other.bassBoostDb &&
          bassBoostFrequencyHz == other.bassBoostFrequencyHz &&
          bassBoostQ == other.bassBoostQ &&
          bandGainsDb == other.bandGainsDb;
}
