// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `channels`, `current_span_len`, `next`, `sample_rate`, `size_hint`, `total_duration`, `try_seek`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `open`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfmpegAudioSource>>
abstract class FfmpegAudioSource implements RustOpaqueInterface {
  Future<void> seekTo({required Duration position});

  Future<Duration?> totalDuration();
}
