// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_square_thumbnail`, `current_time_millis`, `file_token`, `path_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> updateTrackMetadata({
  required String path,
  required TrackMetadataUpdate metadata,
}) => RustLib.instance.api.crateApiSimpleMetadataUpdateTrackMetadata(
  path: path,
  metadata: metadata,
);

Future<TrackMetadataUpdate> getTrackMetadata({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataGetTrackMetadata(path: path);

Future<AudioDetails> getAudioDetails({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataGetAudioDetails(path: path);

Future<void> removeAllTags({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataRemoveAllTags(path: path);

Future<TrackArtworkResult> generateTrackArtwork({
  required String path,
  Uint8List? artworkBytes,
  required String cacheRootPath,
  required bool saveLargeArtwork,
  required int thumbnailSize,
  required int meshStylePreset,
  required double hueCohesion,
  required double paletteBlurRadius,
  required double meshMuddyPenaltyMultiplier,
  required double meshPopulationStrength,
  required double meshContrastStrength,
  required double meshHarmonyStrength,
  required double meshVibrancyStrength,
}) => RustLib.instance.api.crateApiSimpleMetadataGenerateTrackArtwork(
  path: path,
  artworkBytes: artworkBytes,
  cacheRootPath: cacheRootPath,
  saveLargeArtwork: saveLargeArtwork,
  thumbnailSize: thumbnailSize,
  meshStylePreset: meshStylePreset,
  hueCohesion: hueCohesion,
  paletteBlurRadius: paletteBlurRadius,
  meshMuddyPenaltyMultiplier: meshMuddyPenaltyMultiplier,
  meshPopulationStrength: meshPopulationStrength,
  meshContrastStrength: meshContrastStrength,
  meshHarmonyStrength: meshHarmonyStrength,
  meshVibrancyStrength: meshVibrancyStrength,
);

class AudioDetails {
  final String formatName;
  final String codecName;
  final PlatformInt64 durationMs;
  final int bitrate;
  final int sampleRate;
  final int channels;
  final int? bitDepth;
  final String bitrateMode;
  final PlatformInt64 fileSize;

  const AudioDetails({
    required this.formatName,
    required this.codecName,
    required this.durationMs,
    required this.bitrate,
    required this.sampleRate,
    required this.channels,
    this.bitDepth,
    required this.bitrateMode,
    required this.fileSize,
  });

  static Future<AudioDetails> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataAudioDetailsDefault();

  @override
  int get hashCode =>
      formatName.hashCode ^
      codecName.hashCode ^
      durationMs.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitDepth.hashCode ^
      bitrateMode.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDetails &&
          runtimeType == other.runtimeType &&
          formatName == other.formatName &&
          codecName == other.codecName &&
          durationMs == other.durationMs &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitDepth == other.bitDepth &&
          bitrateMode == other.bitrateMode &&
          fileSize == other.fileSize;
}

class TrackArtworkResult {
  final bool artworkFound;
  final String? artworkPath;
  final String? thumbnailPath;
  final int? artworkWidth;
  final int? artworkHeight;
  final Uint8List? themeColorsBlob;
  final Uint8List? meshDebugBlob;

  const TrackArtworkResult({
    required this.artworkFound,
    this.artworkPath,
    this.thumbnailPath,
    this.artworkWidth,
    this.artworkHeight,
    this.themeColorsBlob,
    this.meshDebugBlob,
  });

  static Future<TrackArtworkResult> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackArtworkResultDefault();

  @override
  int get hashCode =>
      artworkFound.hashCode ^
      artworkPath.hashCode ^
      thumbnailPath.hashCode ^
      artworkWidth.hashCode ^
      artworkHeight.hashCode ^
      themeColorsBlob.hashCode ^
      meshDebugBlob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackArtworkResult &&
          runtimeType == other.runtimeType &&
          artworkFound == other.artworkFound &&
          artworkPath == other.artworkPath &&
          thumbnailPath == other.thumbnailPath &&
          artworkWidth == other.artworkWidth &&
          artworkHeight == other.artworkHeight &&
          themeColorsBlob == other.themeColorsBlob &&
          meshDebugBlob == other.meshDebugBlob;
}

class TrackMetadataUpdate {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? trackNumber;
  final int? trackTotal;
  final int? discNumber;
  final String? date;
  final int? year;
  final String? comment;
  final String? lyrics;
  final String? composer;
  final String? lyricist;
  final String? performer;
  final String? conductor;
  final String? remixer;
  final List<String> genres;
  final List<TrackPicture> pictures;

  const TrackMetadataUpdate({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.trackNumber,
    this.trackTotal,
    this.discNumber,
    this.date,
    this.year,
    this.comment,
    this.lyrics,
    this.composer,
    this.lyricist,
    this.performer,
    this.conductor,
    this.remixer,
    required this.genres,
    required this.pictures,
  });

  static Future<TrackMetadataUpdate> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackMetadataUpdateDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      trackNumber.hashCode ^
      trackTotal.hashCode ^
      discNumber.hashCode ^
      date.hashCode ^
      year.hashCode ^
      comment.hashCode ^
      lyrics.hashCode ^
      composer.hashCode ^
      lyricist.hashCode ^
      performer.hashCode ^
      conductor.hashCode ^
      remixer.hashCode ^
      genres.hashCode ^
      pictures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadataUpdate &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          trackNumber == other.trackNumber &&
          trackTotal == other.trackTotal &&
          discNumber == other.discNumber &&
          date == other.date &&
          year == other.year &&
          comment == other.comment &&
          lyrics == other.lyrics &&
          composer == other.composer &&
          lyricist == other.lyricist &&
          performer == other.performer &&
          conductor == other.conductor &&
          remixer == other.remixer &&
          genres == other.genres &&
          pictures == other.pictures;
}

class TrackPicture {
  final Uint8List bytes;
  final String mimeType;
  final String pictureType;
  final String? description;

  const TrackPicture({
    required this.bytes,
    required this.mimeType,
    required this.pictureType,
    this.description,
  });

  static Future<TrackPicture> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackPictureDefault();

  @override
  int get hashCode =>
      bytes.hashCode ^
      mimeType.hashCode ^
      pictureType.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPicture &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          mimeType == other.mimeType &&
          pictureType == other.pictureType &&
          description == other.description;
}
