// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `argb`, `average_color`, `build_square_thumbnail`, `build_theme_colors_blob`, `can_split`, `color_count`, `current_time_millis`, `dark_muted`, `dark_vibrant`, `extract_embedded_artwork_with_id3`, `extract_embedded_artwork_with_lofty`, `extract_embedded_artwork`, `file_token`, `find_split_point`, `first_extended_text_value`, `first_tag_value`, `first_text_frame_value`, `fit_minimum_box`, `from_box`, `generate_palette_score`, `get_max_scored_palette_color`, `id3_picture_type_to_label`, `into_inner`, `light_muted`, `light_vibrant`, `lofty_picture_type_to_label`, `longest_dimension`, `muted`, `new`, `new`, `new`, `normalize_weights`, `pack_rgb`, `palette_targets`, `path_to_string`, `quantize_histogram`, `quantize_palette_colors`, `quantize_rgb`, `read_track_metadata_with_id3`, `read_track_metadata_with_lofty`, `rgb_to_hsl`, `select_theme_colors`, `should_ignore_color`, `should_score_for_target`, `should_use_id3`, `split_box`, `unpack_rgb`, `update_track_metadata_with_id3`, `update_track_metadata_with_lofty`, `vibrant`, `volume`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ColorComponent`, `ColorVolumeBox`, `HslColor`, `PaletteColor`, `PaletteTarget`, `PriorityColorBox`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`

Future<void> updateTrackMetadata({
  required String path,
  required TrackMetadataUpdate metadata,
}) => RustLib.instance.api.crateApiSimpleMetadataUpdateTrackMetadata(
  path: path,
  metadata: metadata,
);

Future<TrackMetadataUpdate> getTrackMetadata({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataGetTrackMetadata(path: path);

Future<TrackArtworkResult> generateTrackArtwork({
  required String path,
  required String cacheRootPath,
  required bool saveLargeArtwork,
  required int thumbnailSize,
}) => RustLib.instance.api.crateApiSimpleMetadataGenerateTrackArtwork(
  path: path,
  cacheRootPath: cacheRootPath,
  saveLargeArtwork: saveLargeArtwork,
  thumbnailSize: thumbnailSize,
);

Future<void> removeAllTags({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataRemoveAllTags(path: path);

class TrackArtworkResult {
  final bool artworkFound;
  final String? artworkPath;
  final String? thumbnailPath;
  final int? artworkWidth;
  final int? artworkHeight;
  final Uint8List? themeColorsBlob;

  const TrackArtworkResult({
    required this.artworkFound,
    this.artworkPath,
    this.thumbnailPath,
    this.artworkWidth,
    this.artworkHeight,
    this.themeColorsBlob,
  });

  static Future<TrackArtworkResult> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackArtworkResultDefault();

  @override
  int get hashCode =>
      artworkFound.hashCode ^
      artworkPath.hashCode ^
      thumbnailPath.hashCode ^
      artworkWidth.hashCode ^
      artworkHeight.hashCode ^
      themeColorsBlob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackArtworkResult &&
          runtimeType == other.runtimeType &&
          artworkFound == other.artworkFound &&
          artworkPath == other.artworkPath &&
          thumbnailPath == other.thumbnailPath &&
          artworkWidth == other.artworkWidth &&
          artworkHeight == other.artworkHeight &&
          themeColorsBlob == other.themeColorsBlob;
}

class TrackMetadataUpdate {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? trackNumber;
  final int? trackTotal;
  final int? discNumber;
  final String? date;
  final int? year;
  final String? comment;
  final String? lyrics;
  final String? composer;
  final String? lyricist;
  final String? performer;
  final String? conductor;
  final String? remixer;
  final List<String> genres;
  final List<TrackPicture> pictures;

  const TrackMetadataUpdate({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.trackNumber,
    this.trackTotal,
    this.discNumber,
    this.date,
    this.year,
    this.comment,
    this.lyrics,
    this.composer,
    this.lyricist,
    this.performer,
    this.conductor,
    this.remixer,
    required this.genres,
    required this.pictures,
  });

  static Future<TrackMetadataUpdate> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackMetadataUpdateDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      trackNumber.hashCode ^
      trackTotal.hashCode ^
      discNumber.hashCode ^
      date.hashCode ^
      year.hashCode ^
      comment.hashCode ^
      lyrics.hashCode ^
      composer.hashCode ^
      lyricist.hashCode ^
      performer.hashCode ^
      conductor.hashCode ^
      remixer.hashCode ^
      genres.hashCode ^
      pictures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadataUpdate &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          trackNumber == other.trackNumber &&
          trackTotal == other.trackTotal &&
          discNumber == other.discNumber &&
          date == other.date &&
          year == other.year &&
          comment == other.comment &&
          lyrics == other.lyrics &&
          composer == other.composer &&
          lyricist == other.lyricist &&
          performer == other.performer &&
          conductor == other.conductor &&
          remixer == other.remixer &&
          genres == other.genres &&
          pictures == other.pictures;
}

class TrackPicture {
  final Uint8List bytes;
  final String mimeType;
  final String pictureType;
  final String? description;

  const TrackPicture({
    required this.bytes,
    required this.mimeType,
    required this.pictureType,
    this.description,
  });

  static Future<TrackPicture> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackPictureDefault();

  @override
  int get hashCode =>
      bytes.hashCode ^
      mimeType.hashCode ^
      pictureType.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPicture &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          mimeType == other.mimeType &&
          pictureType == other.pictureType &&
          description == other.description;
}
