// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_theme_colors_blob_with_options`, `build_theme_colors_blob`, `build_theme_colors_from_image_with_options`

Future<BTreeMapStringU32?> debugBuildThemeColorsFromPixels({
  required List<int> pixels,
  required BigInt channelsPerPixel,
}) => RustLib.instance.api.crateApiSimplePaletteDebugBuildThemeColorsFromPixels(
  pixels: pixels,
  channelsPerPixel: channelsPerPixel,
);

Future<BTreeMapStringU32?> debugBuildThemeColorsFromPixelsWithOptions({
  required List<int> pixels,
  required BigInt channelsPerPixel,
  required ThemePaletteOptions options,
}) => RustLib.instance.api
    .crateApiSimplePaletteDebugBuildThemeColorsFromPixelsWithOptions(
      pixels: pixels,
      channelsPerPixel: channelsPerPixel,
      options: options,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BTreeMap < String , u32 >>>
abstract class BTreeMapStringU32 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ThemePaletteOptions>>
abstract class ThemePaletteOptions implements RustOpaqueInterface {}
